server:
  port: 9091

spring:
  application:
    name: dubbo-provider-application

dubbo:
  # 服务信息
  application:
    name: ${spring.application.name}
    qos-enable: false
    qos-port: 22222
    qos-accept-foreign-ip: false
  # 注册中心地址
  registry:
    address: zookeeper://192.168.2.140:2181
  # 服务提供者的协议
  protocol:
    name: dubbo
    port: 20881
  # 扫描 Dubbo 相关的注解
  scan:
    base-packages: com.clay.dubbo.provider
